wework/ray

packages/core/src/components/text-field/_text-field.scss
=> fix(text-field): change label color to red when error

packages/core/src/global/material-grid/_mixins.scss
[IE11 doesn't support](https://caniuse.com/#search=var()) `var()`
BEFORE:
AFTER:
=> fix(grid-push): for ie11

packages/core/src/components/image/_image.scss
[GROW-7589](https://jira.weworkers.io/browse/GROW-7589)
Updates image caption styling to use ray-body-x-small instead of mono.
**Before:**
**After:**
=> feat(image): update caption styling

docs/components/text-field.md, docs/html/text-area/text-area-multi-row.html, packages/core/src/components/text-field/_text-field.scss, packages/core/stories/text-field.stories.js
when rows are provided to a textarea, the fixed height is removed and set to "auto"
=> feat(textarea): allow multi-row textarea

packages/core/src/global/_variables.scss
Better font-stack for when Apercu Mono cannot load. Which will happen if the user is using a strict ad-blocker.
=> fix(font): update monospace font stack

packages/core/src/components/select/_select.scss, packages/core/stories/select.stories.js
fix #88
The current Select focus/active implementation moves the label up when a select is activated, but if no selection is made (and user clicks off of the select), then the label remains "activated" and only returns back to normal when the select completely loses focus. This change makes it so that the label only moves up if a selection is made.
=> fix(select): don't move label on focus/active

packages/core/src/components/radio-checkbox/_radio-checkbox.scss, packages/core/stories/radio-checkbox.stories.js
The user experience of the active states was a little confusing considering it didnt follow standard visual design
the gifs are slightly old
=> fix(radio-checkbox): improve legebility of radio-checkbox active states

packages/core/src/components/card/_card.scss
The bottom border was not showing in some scenarios in Safari. This `overflow: hidden` doesn't seem needed and fixes it
BEFORE:
AFTER:
=> fix(card): remove overflow hidden for Safari fix

docs/components/select.md, docs/components/text-field.md, docs/html/select/rtl-select-with-prepend.html, docs/html/select/select-with-prepend.html, docs/html/text-field/rtl-text-field-with-prepend.html, docs/html/text-field/text-field-with-prepend.html, packages/core/src/components/select/_select.scss, packages/core/src/components/text-field/_text-field.scss, packages/core/src/global/mixins/_form-items.scss, packages/core/stories/select.stories.js, packages/core/stories/text-field.stories.js
No longer breaking change. Decided to not touch the current `with-icon` implementation and create new styles to support `prepend`.
=> feat(select): prepend support on textfield & select

packages/core/src/components/card/_card.scss
This is done so the card--row matches the original card
=> fix(card): normalize font-weight of card--row heading

docs/foundations/accessibility.md, packages/core/.storybook/config.js, packages/core/src/components/button/_button.scss, packages/core/src/global/_variables.scss, packages/core/src/global/js/accessibility.js, packages/core/src/index.js, packages/core/test/global/accessibility.test.js, packages/core/test/global/boot.test.js, packages/docs-app/src/data/navigation/navigation.json
Adds functionality that disables focus states and hover states for buttons when theyre not applicable. This makes the ux a little cleaner and is inline with peoples expectations for these states
:^)
=> feat(accessibility): only show active states when keyboard navigating

packages/core/src/global/mixins/_breakpoints.scss
Browser width can sometimes land on a half a pixel value. This typically happens when a user zooms in using their browser. 
https://codepen.io/adamraider/pen/MMKdeR
- Add a comment in this file about the half pixel value
- Add a comment in the documentation about how best to use breakpoint values. We want to discourage people from making their own media queries, and caution them as to why
=> fix(breakpoints): add fix for 1px gap edge-case

packages/core/src/components/form-item/_form-item.scss
closes #151 
Repro on Chrome for Windows
=> fix(form-item): ligatures on hints dont get cut off

packages/core/src/components/select/_select.scss, packages/core/stories/select.stories.js
I don't think there is a way to do this with pure css to show an ellipsis. 
BEFORE:
AFTER:
=> fix(select): add space around arrow so doesn't overlap

packages/core/src/components/radio-checkbox/_radio-checkbox.scss
=> fix(checkbox): squishing on small containers

.circleci/config.yml
This could pose security problems due to the open source nature of Ray that anyone can create a PR.
=> ci: disable canary release for review apps

packages/core-react/README.md, packages/core-react/src/components/Type/index.js, packages/core-react/src/components/Type/type.test.js, packages/core-react/stories/type.stories.js, packages/core-react/test/setup.js
https://deploy-preview-175--ray-docs.netlify.com/core-react/storybook/?path=/story/type--default
=> feat(core-react): Add type

packages/core/babel.config.js
specifically [`Event()` is not supported by IE ](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event#Browser_compatibility)
This is causing this error:
=> fix: add browser support to ray-core

packages/core/src/components/select/index.js
babel doesn't transpile `new Event()` for IE11 :(
so let's do it ourselves using [`createEvent`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent) - tested in Browserstack IE11
=> fix: IE11 issue

packages/core/gulpfile.js, packages/core/package.json, packages/core/src/components/button/_button.scss, packages/core/src/components/fieldset/_fieldset.scss, packages/core/src/components/form-item/_form-item.scss, packages/core/src/components/image/_image.scss, packages/core/src/components/radio-pill/_radio-pill.scss, packages/core/src/components/table/_table.scss, packages/core/src/components/tabs/_tabs.scss, packages/core/src/global/mixins/_form-items.scss
This adds some api to the npm package, it allows users to import the css of any individual component without importing the entire css package.
Also adds some export guards for components that were missing it.
The export guard makes it so that the css will never be duplicated in any build (even a custom user bundle)
=> refactor: componentize core components

docs/components/chip.md, packages/core/src/components/chip/index.js, packages/core/test/components/chip.test.js
Emits a change event in `onClick` and `onSpace` so consumers can set event listeners for just the `change` event. Also adds a `set` method that allows consumers to set the active state of the chip
=> fix: adds set method and change event for chip

packages/core-react/src/components/Button/index.js
Wraps the button component in a forward ref so that consumers have the option of passing a ref if necessary. This is a crucial part of adding required a11y to the incoming tabs.
=> feat(core-react): wrap button in forward ref

packages/core-react/index.d.ts
Adds typescript types for `Image` in `core-react`.
=> feat(core-react): add types for image

packages/product-react/src/components/Select/index.ts, packages/product-react/src/components/TextArea/TextArea.test.tsx, packages/product-react/src/components/TextArea/TextArea.tsx, packages/product-react/src/components/TextArea/index.ts, packages/product-react/stories/TextArea.story.tsx
How to run locally
$ yarn storybook
$ yarn test core-components --watch
Nutshell Details:
Semantic wrapper around TextArea element:
=> TextArea to Ray-Product in tsx 

packages/core-react/stories/radio.stories.js, packages/product-react/src/components/Radio/Radio.test.tsx, packages/product-react/src/components/Radio/Radio.tsx, packages/product-react/src/components/Radio/index.ts, packages/product-react/src/index.ts, packages/product-react/stories/radio.story.tsx
Ray Component: https://ray.wework.com/components/radio/
How to run locally
$ yarn storybook
$ yarn test core-components --watch
Nutshell Details:
Semantic wrapper around Radio element:
=> Feat(ray-product):Added Radio in tsx format 

packages/core/package.json, packages/core/src/global/js/polyfills.js, packages/core/src/index.js, packages/docs-app/package.json, packages/docs-app/src/polyfills/index.js, packages/product-react/package.json, yarn.lock
Was getting errors when deploying the docs-app:
This seems to be due to updates made to `core-js`: https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
This PR updates the import paths to be `core-js` so that it polyfills all `core-js` features
=> fix(docs-deploy): update how core-js is imported

.circleci/config.yml
adds a maxWorkers flag to prevent out of memory errors while running tests in CI.
=> chore: add max worker flag to tests in ci

docs/html/dropdown/dropdown--compact.html, docs/html/dropdown/dropdown--error.html, docs/html/dropdown/dropdown--optgroups.html, docs/html/dropdown/dropdown--with-icon.html, docs/html/dropdown/dropdown--with-placeholder.html, docs/html/dropdown/dropdown--with-prepend.html, docs/html/dropdown/dropdown.html, docs/html/dropdown/rtl-dropdown--compact.html, docs/html/dropdown/rtl-dropdown--error.html, docs/html/dropdown/rtl-dropdown--optgroups.html, docs/html/dropdown/rtl-dropdown--with-icon.html, docs/html/dropdown/rtl-dropdown--with-placeholder.html, docs/html/dropdown/rtl-dropdown.html, docs/html/dropdown/rtl-dropdwon--with-prepend.html, packages/core/src/components/dropdown/constants.js, packages/core/src/components/dropdown/index.js, packages/core/test/components/dropdown.test.js, packages/core/test/fixtures/dropdown/index.js
Use plain `<div>` instead of `<template>` to support IE11 without polyfills
Add condition to support case when `<select>` `[selectedIndex] === -1` This case is specific for a IE browsers.
See docs: [https://deploy-preview-259--ray-docs.netlify.com/](https://deploy-preview-259--ray-docs.netlify.com/)
=> Fix issues related to IE11 compatibility

packages/core/src/components/dropdown/constants.js, packages/core/src/components/dropdown/index.js, packages/core/test/components/dropdown.test.js, packages/core/test/fixtures/dropdown/index.js
**Bug with markup duplication observed at: https://ray.wework.com/components/dropdown/**
Root cause: Due to frequent update of Gatsby React component and possibility that DOM element (which used as Key to differ instances) may fail, so possible multi-instantiation of specific component. (Which may lead to creating exceeding markup in case of Dropdown component).
See screenshot 
**Component enhancement as a part of solution:**
Now Dropdown will check markup that needs to be added to layout, if it already been placed (by hand, or by previous instance).
Added tests to check this specific case.
Test URL: https://deploy-preview-261--ray-docs.netlify.com/components/dropdown/
=> Dropdown Enhancement: Markup re-usage

.circleci/config.yml, README.md, RELEASING.md, docs/faq.md, docs/getting-started.md, packages/core/src/components/chip/index.js
- Updates the "Getting Started" page of the docs site to be a little clearer on how to import and use the library
- Updates the "Releasing" readme to be a little clearer on how releasing/publishing works
- Removes the `test-visual-regression` job from CircleCI: this is essentially a no-op, so no point wasting CircleCI resources on it
- Removes the `publish-dsm` job from CircleCI: I confirmed with Dana that we are no longer using Invision DSM
- Makes a trivial code change in the `core` package so that we can test that auto-publishing is working
=> Update docs and remove unnecessary CI jobs
