wework/ray

- packages/core/src/global/_typography.scss
> fix(typography): update margin-bottom of h4-h6

- docs/components/card.md
- docs/html/card/card--link.html
- docs/html/card/card.html
- packages/core/src/components/card/_card.scss
- packages/core/src/global/_typography.scss
- packages/core/stories/card.stories.js
This reverts commit 91666a3b2b9fc93acdee8d43796dfc334a3e5120.
https://deploy-preview-15--ray-docs.netlify.com/components/card/
https://deploy-preview-15--ray-docs.netlify.com/storybook/?path=/story/card--card-link-image-on-top
Hover state:
> fix(card): add card link modifier

- docs/html/card/card--link.html
- docs/html/card/card.html
- packages/core/src/components/card/_card.scss
- packages/core/stories/card.stories.js
> fix(card): add heading element

- README.md
BREAKING CHANGE: release v1.0.0
> docs: remove warning from readme

- packages/core/.storybook/config.js
- packages/core/src/global/js/boot.js
- packages/core/src/index.js
- packages/core/test/global/boot.test.js
> refactor(boot.js): encapsulate logic for easier testing

- packages/core/src/global/js/settings.js
- packages/core/src/index.js
- packages/core/test/index.test.js
just blindly merge this don't ask any questions please, thank you
> feat(settings): export breakpoints from settings

- .eslintrc.js
- docs/components/breadcrumb.md
- docs/html/breadcrumb/breadcrumbs.html
- packages/core/src/components/breadcrumb/_breadcrumb.scss
- packages/core/src/ray-core.scss
- packages/core/stories/breadcrumb.stories.js
- packages/core/stories/card.stories.js
- packages/core/stories/typography.stories.js
- packages/docs-app/src/data/navigation/navigation.json
https://weworkdesign.invisionapp.com/d/main#/console/16513898/361720027/preview
Context: https://wework.slack.com/archives/C03KWQXMT/p1557506338111600?thread_ts=1557495995.101500&cid=C03KWQXMT
> feat(breadcrumb): add breadcrumb component and examples

- .editorconfig
- packages/core/src/components/select/_select.scss
- packages/core/src/components/select/constants.js
- packages/core/src/components/select/index.js
- packages/core/src/components/text-field/_text-field.scss
- packages/core/src/components/text-field/constants.js
- packages/core/src/components/text-field/index.js
- packages/core/src/global/mixins/_form-items.scss
- packages/core/stories/select.stories.js
- packages/core/stories/text-field.stories.js
- packages/core/test/components/select.test.js
- packages/core/test/components/text-field.test.js
- packages/core/test/fixtures/select/index.js
- packages/core/test/fixtures/text-field/index.js
for required text-field and selects, the label will automatically get an asterik *
> fix: add required support for labels

- packages/core/src/components/radio-pill/_radio-pill.scss
> fix(radio-pill): add focus state and change text color

- packages/core/src/components/breadcrumb/_breadcrumb.scss
> fix(breadcrumb): remove scroll glitch and increase arrow size

- docs/components/tag.md
- docs/html/tag/tag-link.html
- packages/core/src/components/tag/_tag.scss
- packages/core/stories/tag.stories.js
> fix(tag): add link styles

- packages/core/src/global/js/boot.js
- packages/core/test/global/boot.test.js
and add test coverage around the initializeComponents logic
> test(boot): up coverage

- packages/core/src/components/card/_card.scss
Updates vertical card padding, as per design: https://weworkdesign.invisionapp.com/d/main#/console/17490718/362543408/preview
> fix(card): update card padding

- packages/core/src/components/breadcrumb/_breadcrumb.scss
- packages/core/src/global/_base.scss
- packages/core/src/global/_variables.scss
https://deploy-preview-104--ray-docs.netlify.com/components/breadcrumb/
>  fix(breadcrumb): line-height problems

- packages/core/stories/card.stories.js
The random graphics are triggering chromatic changes on every build
> test: update card graphics to be static

- packages/core/src/components/radio-checkbox/_radio-checkbox.scss
> fix(radio): move dot to correct position on rtl

- DEVELOP.md
- README.md
- docs/foundations/colors.md
- docs/foundations/typography.md
> docs: add DEVELOP.md

- README.md
- commitlint.config.js
- package.json
- yarn.lock
Contributors should not be expected to learn this convention. It should be up to the ray-maintainers, to enforce this practice (and write proper descriptions) when `squash & merging`.
> chore: remove commitlint

- packages/core/src/components/radio-checkbox/_radio-checkbox.scss
Checkbox wasn't displaying properly.
> fix(checkbox): add relative positioning for checkmark

- .circleci/config.yml
- better caching of node_modules by persisting them to the workspace
- leverage `git diff` to fail a build if yarn-lock is out of sync
- improve naming convention
- parallelize unit tests and visual tests
> ci: improve ci speeds and clean up

- docs/index.md
- packages/docs-app/src/components/Layouts/index.js
- packages/docs-app/src/components/PageHeader/PageHeader.js
- packages/docs-app/src/components/Search/index.js
- packages/docs-app/src/components/SideNav/SideNav.js
- packages/docs-app/src/components/SideNav/side-nav.scss
- packages/docs-app/src/html.js
- packages/docs-app/src/styles/_page.scss
- packages/docs-app/src/templates/page.js
> docs: add search bar

- docs/components/grid.md
Was seeing a lot of improper use of these classes. These rules should help clear up some ambiguity.
> docs: add rules on how to use grid

- packages/core/src/global/_colors.scss
> fix(colors): make ray-color-gray-10 slightly darker

- packages/docs-app/src/components/CodeExample/code-example.scss
- packages/docs-app/src/components/SideNav/side-nav.scss
- packages/docs-app/src/styles/index.scss
- packages/docs-app/src/styles/syntax.scss
> docs: some design updates

- packages/core/src/components/card/_card.scss
the border radius wasnt quite working as expected, one of the corners was not round
> fix(card): fixes border-radius on card rows

- .circleci/config.yml
- lerna.json
- packages/rehype-react/package.json
This PR will:
- release a canary release on every commit (including on every pr), pull request commits will be prefixed with `review`
- remove automatic publishing of non-canary releases
> package: canary release on every commit

- docs/components/button.md
- docs/html/button/button--primary--dark.html
- docs/html/button/button--secondary--dark.html
- docs/html/button/button--tertiary--dark.html
- packages/core/src/components/button/_button.scss
- packages/core/stories/button.stories.js
- packages/docs-app/src/components/CodeExample/CodeExample.js
- packages/docs-app/src/components/ComponentCode/ComponentCode.js
- packages/docs-app/src/components/ComponentCode/component-code.scss
- packages/docs-app/src/components/ComponentExample/ComponentExample.js
> feat(button): add dark buttons

- packages/core/src/global/_typography.scss
> fix: add italic support for i tags in running-text

- packages/docs-app/src/components/CodeSnippet/index.js
Before
After
..now just have to fix the same thing with tables lol
> docs: fix code fouc on load

- packages/docs-app/package.json
- yarn.lock
> chore(deps): remove yarn as an explicit package on docs-app

- packages/core/src/components/select/_select.scss
> fix(select): fix for ligatures being cutoff

- jest.config.js
- packages/core/jest.config.js
- packages/product-react/.storybook/addons.js
- packages/product-react/.storybook/config.js
- packages/product-react/.storybook/preview-head.html
- packages/product-react/.storybook/webpack.config.js
- packages/product-react/README.md
- packages/product-react/babel.config.js
- packages/product-react/config/rollup.config.js
- packages/product-react/gulpfile.js
- packages/product-react/jest.config.js
- packages/product-react/package.json
- packages/product-react/src/index.js
- packages/product-react/stories/index.stories.js
- packages/product-react/test/index.test.js
- packages/product-react/test/setup.js
- yarn.lock
https://deploy-preview-193--ray-docs.netlify.com/product-react/storybook
> init ray-product pr

- packages/core-react/babel.config.js
- packages/core-react/src/components/Grid/Cell.js
- packages/core-react/src/components/Grid/Container.js
- packages/core-react/src/components/Grid/Grid.js
- packages/core-react/src/components/Grid/grid.test.js
- packages/core-react/src/components/Grid/index.js
- packages/core-react/stories/grid.stories.js
> feat(core-react): add grid

- packages/core-react/src/components/Checkbox/index.js
- packages/core-react/src/components/Radio/index.js
- packages/core-react/src/components/Select/index.js
- packages/core-react/stories/checkbox.stories.js
- packages/core-react/stories/radio.stories.js
- packages/core-react/stories/select.stories.js
needs basic unit tests
demo: https://deploy-preview-197--ray-docs.netlify.com/core-react/storybook/?path=/story/*
> some react components

- packages/core-react/src/components/Button/button.test.js
- packages/core-react/src/components/Button/index.js
- packages/core-react/src/components/Card/index.js
> fix(core-react): add custom class support

- docs/html/select/rtl-select--compact.html
- docs/html/select/rtl-select--error.html
- docs/html/select/rtl-select--with-placeholder.html
- docs/html/select/rtl-select.html
- docs/html/select/select--compact.html
- docs/html/select/select--error.html
- docs/html/select/select--with-placeholder.html
- docs/html/select/select.html
- packages/core/stories/select.stories.js
- packages/core/test/fixtures/select/index.js
corrects spelling from 'pikatchu' to 'pikachu'
> refactor: corrects spelling of pikachu

- packages/core-react/index.d.ts
Add typings for Button in core-react.
> chore(core-react): add typings for button

- packages/core-react/index.d.ts
https://jira.weworkers.io/browse/WEB-815
adds typings for Container, Grid and Cell components
> feat(core-react): add typings to index.d.ts for Container, Grid, & Cell

- packages/core-react/index.d.ts
> chore(core-react): Add typings for checkbox

- packages/core-react/index.d.ts
chore(core-react): Add typings for TextArea
> chore(core-react): Add typings for TextArea

- packages/product-react/.storybook/addons.js
- packages/product-react/.storybook/config.js
- packages/product-react/package.json
- yarn.lock
Add the A11y Storybook addon.
https://www.npmjs.com/package/@storybook/addon-a11y
> chore(core-react): Add Storybook A11y addon

- packages/core-react/index.d.ts
added type definitions for select.
> chore(core-react): Add typings for Select

- packages/core-react/index.d.ts
> chore(core-react): add typings for radio

- packages/core-react/index.d.ts
> chore(core-react): add typings for card

- packages/product-react/src/components/Checkbox/Checkbox.test.tsx
- packages/product-react/src/components/Checkbox/Checkbox.tsx
- packages/product-react/src/components/Checkbox/index.ts
- packages/product-react/stories/Checkbox.story.tsx
Ray Component: https://ray.wework.com/components/checkbox/
How to run locally
$ yarn storybook
$ yarn test core-components --watch
Nutshell Details:
Semantic wrapper around Checkbox element:
<Checkbox />
> converted checkbox from js to tsx in ray-product

- packages/product-react/src/components/Typography/Typography.test.tsx
- packages/product-react/src/components/Typography/Typography.tsx
- packages/product-react/src/components/Typography/index.ts
- packages/product-react/stories/Typography.story.tsx
Typography component
https://ray.wework.com/foundations/typography/
How to run locally
$ yarn storybook
$ yarn test product-react --watch
Nutshell Details:
Semantic wrapper around Type element:
> Feat(ray-product):Added Typography in tsx format

- docs/components/text-field.md
- packages/core/src/components/text-field/_text-field.scss
- packages/core/src/global/mixins/_form-items.scss
- packages/core/stories/text-field.stories.js
Proposal to add "append" addon, that works like existing "prepend" one. In order to avoid of modifying ray components in `www-website` project. For examples see docs/storybook
> feat(core): Add support for append addon which works like prepend one

- .circleci/config.yml
- packages/core/.dsmrc
- packages/core/.storybook/addons.js
- packages/core/.storybook/config.js
- packages/core/package.json
- packages/core/stories/button.stories.js
- yarn.lock
- update storybook versions (dsm requires 5.1.0>)
- add dsm integration to core storybook
- add button dsm link
> chore: setup dsm

- docs/components/dropdown.md
- docs/html/dropdown/dropdown--compact.html
- docs/html/dropdown/dropdown--error.html
- docs/html/dropdown/dropdown--optgroups.html
- docs/html/dropdown/dropdown--with-icon.html
- docs/html/dropdown/dropdown--with-placeholder.html
- docs/html/dropdown/dropdown--with-prepend.html
- docs/html/dropdown/dropdown.html
- docs/html/dropdown/rtl-dropdown--compact.html
- docs/html/dropdown/rtl-dropdown--error.html
- docs/html/dropdown/rtl-dropdown--optgroups.html
- docs/html/dropdown/rtl-dropdown--with-icon.html
- docs/html/dropdown/rtl-dropdown--with-placeholder.html
- docs/html/dropdown/rtl-dropdown.html
- docs/html/dropdown/rtl-dropdwon--with-prepend.html
- packages/core/src/components/dropdown/_dropdown.scss
- packages/core/src/components/dropdown/constants.js
- packages/core/src/components/dropdown/index.js
- packages/core/src/components/index.js
- packages/core/src/ray-core.scss
- packages/core/stories/dropdown.stories.js
- packages/core/test/components/dropdown.test.js
- packages/core/test/fixtures/dropdown/index.js
- packages/docs-app/src/data/navigation/navigation.json
Dropdown component for ray framework. When default <select> is not enough. Works as wrapper-enchancer for <select> component. Fallback as `.ray-select` if JS is not applied for some reason.
https://deploy-preview-252--ray-docs.netlify.com/
> Ihor/ray core/rich dropdown component

- docs/html/dropdown/dropdown--error.html
- docs/html/dropdown/rtl-dropdown--error.html
- packages/core/src/components/dropdown/index.js
- packages/core/stories/dropdown.stories.js
- packages/core/test/components/dropdown.test.js
Fixed event propagation for onClick handler and provided correct target for option click handler
> Event propagation fix for Dropdown component

- .circleci/config.yml
- packages/core/.storybook/config.js
- packages/core/package.json
- packages/core/stories/card.stories.js
- packages/core/stories/typography.stories.js
- packages/docs-app/src/components/Search/index.js
- yarn.lock
> Remove chromatic

- packages/core/src/components/radio-pill/_radio-pill.scss
- packages/core/src/global/_colors.scss
- packages/core/src/ray-exports.scss
JIRA: [MPWW-13141](https://jira.weworkers.io/browse/MPWW-13141)
> MPWW-13141: Move updated radio pill group styles to Ray
